# Hola Esto es una prueba para ver si funciona todo

In [5]:
print("Hola esto es una prueba de Colab, Google Drive, GitHub")

Hola esto es una prueba de Colab, Google Drive, GitHub

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('./loan_data.csv.gz')

In [8]:
df

       Unnamed: 0       status  loan_amnt  ...     home_   emp_len_  borrower_score
0               1  Charged Off       2500  ...      RENT   > 1 Year            0.65
1               2  Charged Off       5600  ...       OWN   > 1 Year            0.80
2               3  Charged Off       5375  ...      RENT   > 1 Year            0.60
3               4  Charged Off       9000  ...      RENT   > 1 Year            0.50
4               5  Charged Off      10000  ...      RENT   > 1 Year            0.55
...           ...          ...        ...  ...       ...        ...             ...
45337       45338   Fully Paid       8000  ...      RENT   > 1 Year            0.35
45338       45339   Fully Paid       2000  ...  MORTGAGE   > 1 Year            0.50
45339       45340   Fully Paid       4375  ...  MORTGAGE   > 1 Year            0.55
45340       45341   Fully Paid       8000  ...  MORTGAGE   > 1 Year            0.65
45341       45342   Fully Paid      35000  ...  MORTGAGE   > 1 Year            0.50

[45342 rows x 21 columns]